#!/bin/bash
#SBATCH --partition main                         # Partition name
#SBATCH --time 5-11:30:00                        # Job time limit
#SBATCH --job-name merge_dfs               # Job name
#SBATCH --output my_job-id-%J.out                ### output log for running job - %J is the job number variable
#SBATCH --mail-user=reutme@post.bgu.ac.il        # Email for notifications
#SBATCH --mail-type=END,FAIL                     # Notification types
#SBATCH --gpus=0
#SBATCH --mem=128G                               # Memory allocation
#SBATCH --cpus-per-task=4                        # CPUs per task

### Print SLURM variables
echo "SLURM_JOBID=$SLURM_JOBID"

### Activate the Conda environment
module load anaconda
source activate muscle_diff

### Execute Python script with the array index
python /home/reutme/Big_data/final_project/code/merge_all_dfs.py 
